entrypoint: gunicorn -b :$PORT main:app
runtime: python
env: flex

runtime_config:
  python_version: 3
env_variables:
  CLOUD_STORAGE_BUCKET: dataset_models
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

liveness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  initial_delay_sec: 500

readiness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 2500