entrypoint: gunicorn -b :$PORT main:app
runtime: python
env: flex

runtime_config:
    python_version: 3
env_variables:
    CLOUD_STORAGE_BUCKET: dataset_models

handlers:
- url: /models
  static_dir: models
  
